# Generated by Django 3.0.1 on 2020-01-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=50)),
                ('authorname', models.CharField(max_length=50)),
                ('Publication', models.CharField(max_length=50)),
                ('Isbn', models.CharField(max_length=50)),
                ('imag', models.ImageField(blank=True, upload_to='images')),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='regData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('college_roll', models.IntegerField()),
                ('batch', models.CharField(default='none', max_length=80)),
                ('branch', models.CharField(default='none', max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.IntegerField()),
                ('cpassword', models.IntegerField()),
            ],
        ),
    ]
